### ISSUE TITLE
Mailtrain v2 Beta unable to upload images.

### ISSUE THREAD

**Issue by devlarjay** [Mailtrain-org/mailtrain#515]
Hello!

Sorry to bother but may I ask your help since I am not able to upload images in any of the editor nor the image upload on files tab. I might have miss something but I am using an Ubuntu 18.04 on DigitalOcean.

Kindly please advice please?

Thanks,
Larry

**Comment by devlarjay** [comment]
BTW, I am having a 500 Internal Server Error. :(

**Comment by bures** [comment]
There was a problem with incorrect owner of the files directory. This was fixed in commit cfdcaf65d8adf1cbaf0fe5875a214229bb74431c . Could you please check that you have the most up-to-date version?

Thanks.

**Comment by devlarjay** [comment]
I believe I have, @bures since I followed the readme with git checkout development

Is it possible to have this fix on my end or should I redo installing it on a fresh image from DigitalOcean?

**Comment by bures** [comment]
Just try git pull in the root folder of Mailtrain to see if it pulls anything. If it doesn't, please describe step by step how to reproduce the error.

**Comment by devlarjay** [comment]
Thanks for your prompt reply @bures I really appreciate it! 👍 

I tried git pull but as expected I have the latest version. As for the error, I just tried creating a template with mosaico editor, tried to upload an image but no luck uploading. I tried to upload using the files tab but still no luck and it's returning a 500 Internal Error.
Kindly see image for your reference:

![image](https://user-images.githubusercontent.com/46402579/50726907-3cff5b00-114e-11e9-87d9-dd4f4117c0fd.png)

**Comment by bures** [comment]
That's strange. Could you please add the following line in server/app-builder.js (line 373)
```
console.log(err)
```

The resulting file should look like:
```
        app.use((err, req, res, next) => {
            if (!err) {
                return next();
            }
console.log(err)
            if (req.needsRESTJSONResponse) {
                const resp = {
                    message: err.message,
                    error: {}
                };
```

Then please send me the  log produced by the server. If you are launching it via systemctl, you can view the output by `journalctl -xe`

**Comment by devlarjay** [comment]
Hi @bures, following your lead. It seems that I am having a folder permission error. I believe that's what preventing me from uploading the images. Kindly see attached for your reference:

![image](https://user-images.githubusercontent.com/46402579/50732606-63a6ab80-11b9-11e9-936c-2fe9b5630df4.png)

**Comment by bures** [comment]
Could you please do the following and send me the result?
```
ls -laZR /opt/mailtrain/server/files
```

**Comment by devlarjay** [comment]
Hi @bures kindly see attached for the results

![image](https://user-images.githubusercontent.com/46402579/50734327-82686a80-11d8-11e9-9716-be331cb3896c.png)

![image](https://user-images.githubusercontent.com/46402579/50734331-9ca24880-11d8-11e9-8443-26ca0b5812a4.png)

Though I'm not so sure that this is accurate. I tried to chmod already in mailtrain folder to check if this will be working.

**Comment by devlarjay** [comment]
Yup, chmod works. =))

**Comment by bures** [comment]
The problem is that /opt/mailtrain/files is owned by root.root. The strange thing is that Mailtrain should fix the permission when it starts.

Anyway, try to do `chown mailtrain.mailtrain -R /opt/mailtrain`

There should be no need to do the chmod 777. You can remove the permissions for 'others' if you like. 

Thanks.

**Comment by devlarjay** [comment]
Got it @bures really appreciate this one. 💯 

Removed the permissions as well. Woot! Really glad about mailtrain v2! 🥇

**Comment by bures** [comment]
Excellent. Thanks.

**Comment by Kraftwurm** [comment]
I had the exact same problem and almost gave up on mailtrain... But the "chown mailtrain.mailtrain -R /opt/mailtrain" solved it for me too. (Running on Ubuntu 20.04 by the way...)

**Comment by afanjul** [comment]
Hi @bures, I'm having the same problem, but my added problem is that whenever I change the owner of "files" folder, as soon as I start/restart the mailtrain the folder gets owned by root again...

So, I stop mailtrain, and change permisions:
![image](https://user-images.githubusercontent.com/2046424/133769875-acd113e8-dbb4-49c5-b302-12f3e382631a.png)

Then, I start mailtrain, and this is what I found:
![image](https://user-images.githubusercontent.com/2046424/133769965-ced03e89-e3e7-4daf-86f0-ecfc2c2a732b.png)

And the error is this:
`Sep 17 10:31:14 mailtrain node[18399]: [Error: EACCES: permission denied, open '/opt/mailtrain/server/files/uploaded/07b960d5f427ab1df8bacc6eddacc74c'] {
Sep 17 10:31:14 mailtrain node[18399]:   errno: -13,
Sep 17 10:31:14 mailtrain node[18399]:   code: 'EACCES',
Sep 17 10:31:14 mailtrain node[18399]:   syscall: 'open',
Sep 17 10:31:14 mailtrain node[18399]:   path: '/opt/mailtrain/server/files/uploaded/07b960d5f427ab1df8bacc6eddacc74c',
Sep 17 10:31:14 mailtrain node[18399]:   storageErrors: []
Sep 17 10:31:14 mailtrain node[18399]: }`

The funny thing it's that if I change permissions after the mailtrain restart, it does not work neither.

I don't know if this is related or not but, I usually start the mailtrain as root or using sudo (I think its the correct way), because otherwise the start process complains: 
`@mailtrain:/opt/mailtrain/server$ sudo -u mailtrain service mailtrain start
Failed to start mailtrain.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status mailtrain.service' for details.`

**Comment by rigred** [comment]
Curiously I figured out the fix to this was simply installing the `posix` module with npm.
Without posix module: 
![Screenshot_20230719_004403](https://github.com/Mailtrain-org/mailtrain/assets/5716332/c5db5e3e-be39-49b7-9702-20de79a0fa71)

With posix module:
![Screenshot_20230719_004437](https://github.com/Mailtrain-org/mailtrain/assets/5716332/a6ed2847-fd5f-44c5-98d3-f02eec3b0b27)

This evidently is required for switching the running mailtrain process to check and switch ownership of the created `mailtrain/server/files` directory.

Seems this isn't setup by the bash setup script.
Hope it helps others.
